name: Vote CI
on:
  workflow_dispatch:
  push:
    branches: [dev]
    paths:
      - '.github/workflows/vote-ci.yml'
      - 'pnpm-lock.yaml'
      - 'packages/vote/**'

jobs:
  build:
    name: Build and Deploy to Vercel
    runs-on: ubuntu-22.04
    if: github.repository == 'PatchyVideo/Touhou-Vote'
    environment: Vote-CI
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          check-latest: true

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: |
            - args: [--frozen-lockfile, --strict-peer-dependencies]
        timeout-minutes: 10

      - name: Codegen
        run: pnpm codegen
        working-directory: ./packages/vote
        timeout-minutes: 5

      - name: Build
        run: pnpm build
        working-directory: ./packages/vote
        timeout-minutes: 15

      - name: Deploy to Vercel
        run: npx vercel@latest deploy --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
        working-directory: ./packages/vote/dist
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        timeout-minutes: 5
