scalar Date

type QueryRoot {
  frontendInfo: FEFrontendInfo!
}

type FEFrontendInfo {
  voteData2020: FEVoteData2020!
}

type FEVoteData2020 {
  characters: [FECharacter!]
  games: [FEGame!]
}

type FECharacter {
  name: String!
  group: String!
  appeared: [FEGame!]
  keywords: [String!]
  image: String
}

type FEGame {
  name: String!
  type: String!
  date: Date!
  keywords: [String!]
  image: String
  people: [FECharacter!]
}
